---
# Handlers for docker_engine role

- name: Restart docker
  ansible.builtin.service:
    name: docker
    state: restarted
  become: true
  listen: "restart docker"

- name: Stop docker
  ansible.builtin.service:
    name: docker
    state: stopped
  become: true
  listen: "stop docker"

- name: Ensure Docker service state
  ansible.builtin.systemd:
    name: docker
    state: "{{ docker_engine_service_state }}"
    enabled: "{{ docker_engine_service_enabled }}"
  become: true
