---
galaxy_info:
  author: Alexey Gorynovich
  description: Manage Docker access for users
  license: GPL-3.0-or-later

  min_ansible_version: "2.16"

  platforms:
    - name: AlmaLinux
      versions:
        - "9"
        - "10"
    - name: Rocky
      versions:
        - "9"
        - "10"
    - name: Fedora
      versions:
        - "43"
    - name: Ubuntu
      versions:
        - "24.04"
        - "26.04"
    - name: Debian
      versions:
        - "12"
        - "13"

  galaxy_tags:
    - docker
    - access
    - permissions
    - users

dependencies: []
