---
# tasks file for docker_access

- name: Include preflight checks
  ansible.builtin.include_tasks: preflight.yml

- name: Check if OS is supported
  ansible.builtin.fail:
    msg: "Unsupported OS '{{ ansible_distribution }} {{ ansible_distribution_version }}'. Supported distributions: Ubuntu, Debian, AlmaLinux, Rocky, Fedora"
  when:
    - ansible_distribution not in ['Ubuntu', 'Debian', 'AlmaLinux', 'Rocky', 'Fedora']

- name: Manage Docker access for users
  ansible.builtin.include_tasks: manage-access.yml
