---
- name: Converge
  hosts: all
  become: true
  roles:
    - role: docker_prerequisites
    - role: docker_repository
    - role: docker_engine
    - role: docker_tools
      docker_tools_packages:
        - ctop
        - watch
      docker_tools_install_completion: true
