---
# Variables for Rocky systems

docker_rocky_packages:
  - "{{ 'docker-ce-' + docker_engine_version if docker_engine_version else 'docker-ce' }}"
  - "{{ 'docker-ce-cli-' + docker_engine_version if docker_engine_version else 'docker-ce-cli' }}"
  - containerd.io
