---
# Configure Docker buildx instance

- name: Check if Docker buildx instance exists
  ansible.builtin.command: docker buildx inspect {{ docker_plugins_buildx_instance_name }}
  register: buildx_inspect_result
  changed_when: false
  failed_when: false
  become: true

- name: Create and use Docker buildx instance
  ansible.builtin.command: docker buildx create --name {{ docker_plugins_buildx_instance_name }} --use
  register: buildx_create_result
  changed_when: true
  become: true
  when: buildx_inspect_result.rc != 0

- name: Check current Docker buildx builder
  ansible.builtin.command: docker buildx ls
  register: buildx_ls_result
  changed_when: false
  become: true

- name: Print available buildx builders
  ansible.builtin.debug:
    msg: "Available buildx builders: {{ buildx_ls_result.stdout }}"
