---
# Default variables for docker_repository role
docker_repository_channel: "stable"
docker_repository_base_url: ""
docker_repository_manage_repo: true
docker_repository_gpg_key_checksum: "sha256:1500c1f56fa9e26b9b8f42452a553675796ade0807cdce11975eb98170b3a570"
