---
# defaults file for docker_prerequisites role

# Whether to remove conflicting packages like podman, podman-docker, docker.io, docker-ce
docker_prerequisites_remove_conflicts: true

# Whether to install bash completion for docker
docker_prerequisites_install_completion: false
